#!/bin/bash
# $Id: tbox_updater_static 114033 2026-04-27 09:34:52Z knut.osmundsen@oracle.com $
## @file
# This script runs every min from the www-data crontab
#

die() {
   echo "$0: Fatal error: $*"
   exit 1;
}
SCRIPTDIR=$(dirname "$0")
OUTDIR=/bigssd/localhost/tinderbox/rootdir

cd "${OUTDIR}" || die "cd ${OUTDIR} failed"
sleep 15 &
echo > /tmp/tbox_updater_static.running
sleep 15 &
perl -TI "${SCRIPTDIR}" "${SCRIPTDIR}/tbox_build_static_pages.pl" || die "${SCRIPTDIR}/tbox_build_static_pages.pl failed"
echo > /tmp/tbox_updater_static.last
rm -f /tmp/tbox_updater_static.running
wait
sleep 15 &
echo > /tmp/tbox_updater_static.running
perl -TI "${SCRIPTDIR}" "${SCRIPTDIR}/tbox_build_static_pages.pl" || die "${SCRIPTDIR}/tbox_build_static_pages.pl failed"
echo > /tmp/tbox_updater_static.last
rm -f /tmp/tbox_updater_static.running
wait
sleep 15 &
echo > /tmp/tbox_updater_static.running
perl -TI "${SCRIPTDIR}" "${SCRIPTDIR}/tbox_build_static_pages.pl" || die "${SCRIPTDIR}/tbox_build_static_pages.pl failed"
echo > /tmp/tbox_updater_static.last
rm -f /tmp/tbox_updater_static.running
wait
echo > /tmp/tbox_updater_static.running
perl -TI "${SCRIPTDIR}" "${SCRIPTDIR}/tbox_build_static_pages.pl" || die "${SCRIPTDIR}/tbox_build_static_pages.pl failed"
echo > /tmp/tbox_updater_static.last
rm -f /tmp/tbox_updater_static.running
