#!/bin/bash
# $Id: tbox_updater 114033 2026-04-27 09:34:52Z knut.osmundsen@oracle.com $
## @file
# This script runs every five min from the www-data crontab.
#

die() {
   echo "$0: Fatal error: $*"
   exit 1;
}

SCRIPTDIR=$(dirname "$0")
TBOXLOGDIR=/bigssd/localhost/tinderbox/logs

echo > /tmp/tbox_updater.running
cd "${OUTDIR}" || die "cd ${OUTDIR} failed"

# remove the 304 logs.
psql -qtA tbox -c "select concat('${TBOXLOGDIR}/',machine_id,'/',log) from tbox_build where status = 304;" | xargs --no-run-if-empty rm
psql -q   tbox -c "delete FROM tbox_build where status = 304;"
psql -q   tbox -c "reindex table tbox_build;"

# compress the logs
"${SCRIPTDIR}/tbox_recompress_logs.pl"

# enforce build, vob and png quotas.
#20180301 klaus: disabled, wasn't working right since 20171031 due to lack of delete permission, to be fixed
#/srv/localhost/www/client/tindertux-quota.sh >> /var/log/tindertux-quota.log

echo > /tmp/tbox_updater.last
rm /tmp/tbox_updater.running
