' $Id: audio_testing_framework_components.iuml 113990 2026-04-23 14:00:31Z knut.osmundsen@oracle.com $
'' @file
' UML definition for PlantUML - Audio Testing Framework - Components
'

'
' Copyright (C) 2021-2026 Oracle and/or its affiliates.
'
' This file is part of VirtualBox base platform packages, as
' available from https://www.virtualbox.org.
'
' This program is free software; you can redistribute it and/or
' modify it under the terms of the GNU General Public License
' as published by the Free Software Foundation, in version 3 of the
' License.
'
' This program is distributed in the hope that it will be useful, but
' WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
' General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, see <https://www.gnu.org/licenses>.
'
' SPDX-License-Identifier: GPL-3.0-only
'

@startuml

title Audio Testing Framework - Components
left to right direction

folder "PDM" {
  interface IPDMAudioConnector
  note top of IPDMAudioConnector
    Glue interface for
    guest / host communication
  end note
  interface IHostAudio
  note top of IHostAudio
    Used by the backends to implement
    OS-dependent audio code
  end note
  IHostAudio -down-> [Driver Stack] : register
  IPDMAudioConnector -down-> [Driver Stack] : register
  [Driver Stack]
}

folder "VBoxDD" {
  [Common Audio Test Code]
  note right of [Common Audio Test Code]
    Contains tone generation,
    analysis, glue code, ++
  end note
  [Interface Stubs] -down..> [ALSA Backend] : use
  [Interface Stubs] -down..> [DSound Backend] : use
  [Interface Stubs] -down--> [DrvAudio]
  [Audio Test Service (ATS)] ..> TCPIP : listen
  [Audio Test Service (ATS)] -> [Common Audio Test Code] : use
  [Validation Kit Backend] <-> [Audio Test Service (ATS)] : use
  [Validation Kit Backend] -> [Common Audio Test Code] : use
  [Validation Kit Backend] ..> [DrvAudio] : injects\ninput (upper)
  [ALSA Backend] --> [IHostAudio] : implement
  [DSound Backend] --> [IHostAudio] : implement
  [DrvAudio] --> [IPDMAudioConnector] : implement
  [Mixer] ..-> [IPDMAudioConnector] :use
  [HDA Device] --> [Mixer] : use
}

folder "Validation Kit" {
  folder "Test Drivers" {
    [tdAudioTest.py]
  }

  folder "Utilities" {
    [Validation Kit Audio Test (VKAT)] -> [Interface Stubs] : mock
    [Validation Kit Audio Test (VKAT)] -> [Common Audio Test Code] : use
    [Validation Kit Audio Test (VKAT)] <.. [tdAudioTest.py] : execute on guest
    note bottom of [Validation Kit Audio Test (VKAT)]
      Can also be run on hosts
      to test and validate backends
    end note
  }
}

@enduml