' $Id: audio_output.iuml 113990 2026-04-23 14:00:31Z knut.osmundsen@oracle.com $
'' @file
' UML definition for PlantUML - Audio Output.
'

'
' Copyright (C) 2013-2026 Oracle and/or its affiliates.
'
' This file is part of VirtualBox base platform packages, as
' available from https://www.virtualbox.org.
'
' This program is free software; you can redistribute it and/or
' modify it under the terms of the GNU General Public License
' as published by the Free Software Foundation, in version 3 of the
' License.
'
' This program is distributed in the hope that it will be useful, but
' WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
' General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, see <https://www.gnu.org/licenses>.
'
' SPDX-License-Identifier: GPL-3.0-only
'

@startuml
title Audio output from the guest

participant Guest
participant Device

activate Guest
activate Device
create "LUN #0"
Device -> "LUN #0" : << Attaches >>
activate "LUN #0"
create DrvAudio
"LUN #0" -> DrvAudio : << Creates >>
activate DrvAudio
create Backend
DrvAudio -> Backend : << Initializes >>
activate Backend

== Creation ==

"LUN #0" -> DrvAudio : pfnOpenOut
DrvAudio -> DrvAudio : << Creates stream pair >>
create HstStrmOut
DrvAudio -> HstStrmOut : << Creates >>
HstStrmOut -> Backend : pfnInitOut
create GstStrmOut
DrvAudio -> GstStrmOut : << Creates >>
activate HstStrmOut
activate GstStrmOut
GstStrmOut -> HstStrmOut : << Links to >>
GstStrmOut -> GstStrmOut : << Calculates >>
note right
    Calculates
        - Frequency ratio (based on Hz)
        - Conversion rate
end note
GstStrmOut -> Device : << Sets callbacks >>

== Sending output ==

HstStrmOut -> Device : << Callback (Free) >>
note right : Tells the device about how many bytes it can write
Guest -> Device : << Sending data >>
"LUN #0" -> DrvAudio : pfnWrite
DrvAudio -> Backend : pfnPlayOut

== Destruction ==

HstStrmOut -> Backend : pfnFiniOut

deactivate HstStrmOut
deactivate GstStrmOut

deactivate Backend
deactivate DrvAudio
deactivate Device
deactivate Guest

@enduml
