' $Id: guestdnd.iuml 113990 2026-04-23 14:00:31Z knut.osmundsen@oracle.com $
'' @file
' UML definition for PlantUML - Guest drag'n drop class diagram.
'

'
' Copyright (C) 2014-2026 Oracle and/or its affiliates.
'
' This file is part of VirtualBox base platform packages, as
' available from https://www.virtualbox.org.
'
' This program is free software; you can redistribute it and/or
' modify it under the terms of the GNU General Public License
' as published by the Free Software Foundation, in version 3 of the
' License.
'
' This program is distributed in the hope that it will be useful, but
' WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
' General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, see <https://www.gnu.org/licenses>.
'
' SPDX-License-Identifier: GPL-3.0-only
'

@startuml
title VirtualBox Drag'n Drop

enum DnDAction {
DnDAction_Ignore
DnDAction_Copy
DnDAction_Move
DnDAction_Link
}

enum DnDMode {
DnDMode_Disabled
DnDMode_HostToGuest
DnDMode_GuestToHost
DnDMode_Bidirectional
}

interface IMachine {
+ dndMode() : DnDMode
}

class GuestDnDPrivate {
}

GuestDnDPrivate *-- GuestDnDTarget
GuestDnDPrivate *-- GuestDnDSource

interface IDnDBase {
+ isFormatSupported([in] format : wstring, [return] supported : boolean)
+ addFormats([in] formats : wstring[1 .. *])
+ removeFormats([in] formats : wstring[1 .. *])
+ << readonly >> formats : wstring[0 .. *]
}
IDnDBase <|-- IDnDTarget
IDnDBase <|-- IDnDSource

interface IDnDTarget {
+ enter([in] screenId : unsigned long, [in] x : unsigned long, [in] y : unsigned long, [in] defaultAction : DnDAction, [in] allowedActions : DnDAction[1 .. *], [in] formats : wstring[1 .. *], [return] resultAction : DnDAction)
+ move([in] screenId : unsigned long, [in] x : unsigned long, [in] y : unsigned long, [in] defaultAction : DnDAction, [in] allowedActions : DnDAction[1 .. *], [in] formats : wstring[1 .. *], [return] resultAction : DnDAction)
+ leave([in] screenId : unsigned long)
+ drop([in] screenId : unsigned long, [in] x : unsigned long, [in] y : unsigned long, [in] defaultAction : DnDAction, [in] allowedActions : DnDAction[1 .. *], [in] formats : wstring[1 .. *], [out] format : wstring, [return] resultAction : DnDAction)
+ sendData([in] screenId : unsigned long, [in] format : wstring, [in] data : octet[0 .. *], [return] progress : IProgress)
}
IDnDTarget <|-- GuestDnDTarget

interface IGuest {
+ dndTarget : IDnDTarget
+ dndSource : IDnDSource
}

interface IDnDSource {
+ dragIsPending([in] screenId : unsigned long, [out] formats : wstring[1 ..*], [out] allowedActions : DnDAction[1 .. *], [return] defaultAction : DnDAction)
+ drop([in] format : wstring, [in] action : DnDAction, [return] progress : IProgress)
+ receiveData([return] data : octet[0 .. *])
}
IDnDSource <|-- GuestDnDSource

@enduml
