' $Id: update_api.iuml 113990 2026-04-23 14:00:31Z knut.osmundsen@oracle.com $
'' @file
' UML definition for PlantUML - VirtualBox Update Agent + Manager - Draft
'

'
' Copyright (C) 2022-2026 Oracle and/or its affiliates.
'
' This file is part of VirtualBox base platform packages, as
' available from https://www.virtualbox.org.
'
' This program is free software; you can redistribute it and/or
' modify it under the terms of the GNU General Public License
' as published by the Free Software Foundation, in version 3 of the
' License.
'
' This program is distributed in the hope that it will be useful, but
' WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
' General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, see <https://www.gnu.org/licenses>.
'
' SPDX-License-Identifier: GPL-3.0-only
'

@startuml
title VirtualBox Update Agent + Manager API for VirtualBox 7.0 (7.x as draft)
hide empty description

enum UpdateChannel
{
     Invalid
     Stable
     All
     WithBetas
     WithTesting
}

enum UpdateSeverity
{
     Invalid
     Critical
     Major
     Minor
     Testing
}

enum UpdateState
{
    Invalid
    SettingsChanged
    Available
    NotAvailable
    Downloading
    Downloaded
    Installing
    Installed
    UserInteraction
    Canceled
    Maintenance
    Error
}

abstract class IUpdateAgent
{
    #checkFor(UpdateChannel) : IProgress
    #download(UpdateChannel) : IProgress
    #install(UpdateChannel) : IProgress
    #rollback()
    +getName : wstring
    +getVersion : wstring
    +getOrder : ULONG
    +getDependsOn : SafeArray<wstring>
    +getEnabled : BOOL
    +setEnabled(BOOL)
    +getHidden : BOOL
    +getState : UpdateState
    +setCheckFrequency(wstring)
    +getDownloadURL : wstring
    +getWebURL : wstring
    +getReleaseNotes : wstring
    +getRepositoryURL : wstring
    +setRepositoryURL(wstring, BOOL fIgnoreCerts)
    +getCheckFrequency : wstring
    +setCheckFrequency(wstring)
    +getCheckCount : ULONG
    +setCheckCount(ULONG)
    +getLastCheckDate : wstring
    +setLastCheckDate(wstring)

    __ Events __

    +EventSource : IEventSource
    +UpdateStateChangedEvent : IUpdateAgentEvent
    +UpdateErrorEvent : IUpdateAgentErrorEvent
    +UpdateAvailableEvent : IUpdateAgentAvailableEvent
}

abstract class IUpdateAgentSettingsChangedEvent
{
    +Source   : IEventSource
}

abstract class IUpdateAgentEvent
{
    +Source   : IEventSource
    +enmState : UpdateState
}

abstract class IUpdateAgentErrorEvent
{
    +strMsg : wstring
    +rcErr  : LONG
}

abstract class IUpdateAgentAvailableEvent
{
    +version : wstring
    +channel : UpdateChannel
    +severity : UpdateSeverity
    +downloadURL : wstring
    +webURL : wstring
    +releaseNotes : wstring
}

IEvent <|-- IUpdateAgentEvent
IUpdateAgentEvent <|-- IUpdateAgentSettingsChangedEvent
IUpdateAgentEvent <|-- IUpdateAgentAvailableEvent
IUpdateAgentEvent <|-- IUpdateAgentErrorEvent

note left of IUpdateAgent::rollback
   Will be called when IUpdateAgent::install fails.
end note

note left of IUpdateAgent::getOrder
   Order hint the update component needs to run at, in conjunction with other update components.
end note

note left of IUpdateAgent::getDependsOn
    Array of other update component names this component depends on before being able to get installed.
end note

note left of IUpdateAgent::getHidden
   Defines whether the update is seen in the UI or not.
end note

note left of IUpdateAgent::getState
   Returns the last (current) update state.
end note


package "7.0" {

    class IHost
    {
        UpdateHost : IUpdateAgent
    }
}

package "7.x (Draft)" {

    abstract class IUpdateAgentInteractionEvent
    {
        +strMsg : wstring
        +strButtons : wstring
    }

    IUpdateAgentAvailableEvent <|-- IUpdateAgentInteractionEvent

    class IUpdateManager
    {
        +register(IUpdateAgent)
        +unregister(IUpdateAgent)
        +getAgents : collection IUpdateAgent
    }

    class IVirtualBox
    {
        UpdateManager : IUpdateManager
    }

    IUpdateAgent <|-- IHostUpdateAgent : implements
    IUpdateAgent <|-- IGuestAdditionsUpdateAgent : implements

    class IGuest
    {
        AdditionsUpdateAgent : IGuestAdditionsUpdateAgent
    }

    IUpdateAgent *-- IExtPackManager : composed
}

@enduml
