' $Id: win_host_installer_activity.iuml 113990 2026-04-23 14:00:31Z knut.osmundsen@oracle.com $
'' @file
' UML definition for PlantUML - VirtualBox Windows Host Installer.
'

'
' Copyright (C) 2020-2026 Oracle and/or its affiliates.
'
' This file is part of VirtualBox base platform packages, as
' available from https://www.virtualbox.org.
'
' This program is free software; you can redistribute it and/or
' modify it under the terms of the GNU General Public License
' as published by the Free Software Foundation, in version 3 of the
' License.
'
' This program is distributed in the hope that it will be useful, but
' WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
' General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, see <https://www.gnu.org/licenses>.
'
' SPDX-License-Identifier: GPL-3.0-only
'

@startuml
title VirtualBox Host Installer - Mode: Installation
hide empty description

state cShowLicense <<choice>>
state cAcceptLicense <<choice>>
state cCheckSerial <<choice>>
state cSerialValid <<choice>>
state cShowCustomizeDlg <<choice>>
state cWarnPythonAPI <<choice>>
state cWarnDisconNetIfaces <<choice>>
state cShowCustomize2Dlg <<choice>>
state cInstallComplete <<choice>>

[*] --> VBoxWelcomeDlg

VBoxWelcomeDlg --> cShowLicense : Show license?
cShowLicense --> cCheckSerial : No
cShowLicense --> VBoxLicenseAgreementDlg : Yes

VBoxLicenseAgreementDlg --> cAcceptLicense : Accept license?
cAcceptLicense --> VBoxUserExitDlg : No
cAcceptLicense --> cCheckSerial : Yes

VBoxCheckSerialDlg --> cSerialValid : Serial valid?
cSerialValid --> cShowCustomizeDlg : Yes
cSerialValid --> VBoxWrongSerialDlg : No

VBoxWrongSerialDlg --> VBoxCheckSerialDlg : Serial invalid?
VBoxWrongSerialDlg --> cShowCustomizeDlg : Serial valid
VBoxWrongSerialDlg --> VBoxUserExitDlg : Abort

cCheckSerial --> cShowCustomizeDlg :  Skip serial
cCheckSerial --> VBoxCheckSerialDlg : Check serial?

cShowCustomizeDlg --> VBoxCustomizeDlg : Show customization dialog?
cShowCustomizeDlg --> cShowCustomize2Dlg : Skip customization dialog
VBoxCustomizeDlg --> cWarnDisconNetIfaces : Warn about network interfaces?

cWarnDisconNetIfaces --> cWarnPythonAPI : No
cWarnDisconNetIfaces --> VBoxWarnDisconNetIfacesDlg : Yes

VBoxWarnDisconNetIfacesDlg --> cWarnPythonAPI : Continue
VBoxWarnDisconNetIfacesDlg --> VBoxCancelDlg : Cancel

cWarnPythonAPI --> VBoxWarnPythonDlg : Warn about Python bindings?
cWarnPythonAPI --> cShowCustomize2Dlg : Skip

VBoxWarnPythonDlg --> cShowCustomize2Dlg : Continue
VBoxWarnPythonDlg --> VBoxCancelDlg : Cancel

cShowCustomize2Dlg --> VBoxCustomize2Dlg : Show FE/Qt customization dialog?
cShowCustomize2Dlg --> VBoxVerifyReadyDlg : Skip FE/Qt customization dialog

VBoxCustomize2Dlg --> VBoxVerifyReadyDlg

VBoxVerifyReadyDlg --> Installation : Start installation
VBoxVerifyReadyDlg --> VBoxCancelDlg : Cancel

VBoxCancelDlg --> VBoxUserExitDlg

Installation --> cInstallComplete

cInstallComplete -> VBoxExitDlg : Installation finished
cInstallComplete -> VBoxErrorDlg : Installation failed

VBoxUserExitDlg --> [*]
VBoxErrorDlg  --> [*]
VBoxExitDlg --> [*]

@enduml
